### ISSUE TITLE
MediaInfo step: stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by tiagobnobrega** [aws-solutions-library-samples/video-on-demand-on-aws#14]
Hi,

I deployed the stack and tried to upload a file, it's a 1080p mp4 with 22.6MB. The Media Info lambda function fails. It outputs the following error:

```json
{
  "errorMessage": "stdout maxBuffer exceeded",
  "errorType": "Error",
  "stackTrace": [
    "Socket.<anonymous> (child_process.js:257:14)",
    "emitOne (events.js:96:13)",
    "Socket.emit (events.js:188:7)",
    "readableAddChunk (_stream_readable.js:176:18)",
    "Socket.Readable.push (_stream_readable.js:134:10)",
    "Pipe.onread (net.js:547:20)"
  ]
}
```
My guess, is that child process started to call MediaInfo fails [here](https://github.com/awslabs/video-on-demand-on-aws/blob/6e95e204a827739bced27bdd6693e4939eee42a3/source/mediainfo/lib/mediaInfoCommand.js#L205)

I guess You could pass a maxBuffer parameter to this call. The default value is 200KB if I'm not mistaken. Maybe It shoudl be exported as an environment variable for the lambda function such as "ErrorHandler" is. But I'm not sure this is the problem.

**Comment by tiagobnobrega** [comment]
So... I changed the lambda function to increase "maxBuffer" of child process to 500KB and everything worked fine. I can make a pull request for the change if needed. I would expose this parameter as a enviroment variable with a default of 200KB. It's also possible to change the stack to register this environment variable on lambda creation.

**Comment by thomasphorton** [comment]
Thank you for bringing this to our attention! I've created an item in our internal backlog to add this functionality. If you'd like to submit a pull request, go for it! It'll help others who run into the same issue while we work on prioritization and implementation.

**Comment by thelax24** [comment]
I'm also having this same problem.    Was increasing the "maxBuffer" size the solution?   Where would I go to do this?    I couldn't find a pull request for @tiagobnobrega .      Thanks for any suggestions you can give me on this.

{
    "errorMessage": "MediaInfo.command: https://....../somevideo.mp4 - stdout maxBuffer exceeded",
    "errorType": "Error",
    "stackTrace": [
        "Socket.onChildStdout (child_process.js:328:14)",
        "emitOne (events.js:116:13)",
        "Socket.emit (events.js:211:7)",
        "addChunk (_stream_readable.js:263:12)",
        "readableAddChunk (_stream_readable.js:246:13)",
        "Socket.Readable.push (_stream_readable.js:208:10)",
        "Pipe.onread (net.js:607:20)"
    ]
}
